<?php

namespace CDC\Loja\Test;

use PHPUnit_Framework_TestCase as PHPUnit;

class TestCase extends PHPUnit
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}